name: My First Workflow
on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
            - name: Welcome message
              run: echo "My first GitHub Actions Job"
            
            - name: List Files
              run: ls -altr

            - name: Read File
              run: cat README.md
            

